g++   Uni10.cpp   -std=c++11   -luni10 -larmadillo    


g++   Uni10.cpp   -std=c++11       -fPIC    -I /opt/intel/compilers_and_libraries_2017.1.132/linux/mkl/include -L /opt/intel/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64  -Wl,-rpath=/opt/intel/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64   -pthread  -luni10 -larmadillo


 g++   Uni10.cpp   -std=c++11       -fPIC    -I /opt/intel/mkl/include    -pthread  -luni10 -larmadillo 
 
  g++   Uni10.cpp   -std=c++11       -fPIC       -pthread  -luni10 -larmadillo
  
  g++   Uni10.cpp   -std=c++11  -Ofast   -fPIC    -pthread  -luni10 -larmadillo
